export const FALLBACK_PHRASES = [
  { phrase: "To be or not to be", password: "ToBe@Not2Be!" },
  { phrase: "Look before you leap", password: "LookB4@Leap!" },
  { phrase: "Stay hungry stay foolish", password: "Stay+Hungry5!" },
  { phrase: "Actions speak louder", password: "Act!onsSp34k!" },
  { phrase: "Here comes the sun", password: "H3r3@c0mesSun!" },
  { phrase: "Life is what happens", password: "L!f3@Happens2" },
  { phrase: "May the force be with you", password: "Force@BeWithU7" },
  { phrase: "Knowledge is power", password: "Kn0wl3dg3@Pwr!" },
  { phrase: "Keep calm and carry on", password: "K33pCalm@On+" },
  { phrase: "The best is yet to come", password: "B3st@Y3t2Come!" },
  { phrase: "Time is money", password: "T!me@IsM0n3y$" },
  { phrase: "Love is all you need", password: "Luv@IsAllU-N33d" },
  { phrase: "Just do it", password: "Just@DoIt-100" },
  { phrase: "Think different", password: "Th!nk@D!ff3r3nt" },
  { phrase: "I have a dream", password: "I-Hav3@Dream1" },
  { phrase: "All you need is love", password: "Need@IsLuv-4" },
  { phrase: "Believe you can", password: "B3l!3v3@U-Can1" },
  { phrase: "Change the world", password: "Chang3@W0rld!" },
  { phrase: "Dream big work hard", password: "Dream@WorkHard9" },
  { phrase: "Good vibes only", password: "GoodV!b3s@Only1" },
  // Adding more to reach a decent number for demo
  { phrase: "The quick brown fox", password: "Qu!ck@Br0wnFox1" },
  { phrase: "Hello world", password: "H3ll0@W0rld!1" },
  { phrase: "Open sesame", password: "Op3n@S3sam3!1" },
  { phrase: "Carpe diem", password: "Carp3@D!em!1" },
  { phrase: "Eureka", password: "Eur3ka!777" },
];
