export const FALLBACK_PHRASES = [
  { phrase: "To be or not to be", password: "ToBe@or@Not2Be!!" },
  { phrase: "Look before you leap", password: "LookB4uLeap@777" },
  { phrase: "Stay hungry stay foolish", password: "Stay+Hungry+555" },
  { phrase: "Actions speak louder", password: "ActionsSpeak+88" },
  { phrase: "Here comes the sun", password: "H3reComesTheSun!" },
  { phrase: "Life is what happens", password: "L!feHappens@222" },
  { phrase: "May the force be with you", password: "ForceBeWithU@77" },
  { phrase: "Knowledge is power", password: "KnowL3dge@Pwr!!" },
  { phrase: "Keep calm and carry on", password: "K33pCa7m@Carry+" },
  { phrase: "The best is yet to come", password: "B3st@Y3t2Come!!" },
  { phrase: "Time is money", password: "T!me@isMoney$$$" },
  { phrase: "Love is all you need", password: "Luv@isA77UN33d!" },
  { phrase: "Just do it", password: "Just@Doit@88888" },
  { phrase: "Think different", password: "Th!nk@D!ff3rent!" },
  { phrase: "I have a dream", password: "i-HaveADream@77" },
  { phrase: "All you need is love", password: "A77UNeedisLuv+4" },
  { phrase: "Believe you can", password: "B37ieveUCan@777" },
  { phrase: "Change the world", password: "ChangeTheWorld!" },
  { phrase: "Dream big work hard", password: "Dream@WorkHard9" },
  { phrase: "Good vibes only", password: "GoodV!b3s@On7y7" },
  { phrase: "The quick brown fox", password: "Qu!ck@BrownFox7" },
  { phrase: "Hello world", password: "He77o@Wor7d!!!7" },
  { phrase: "Open sesame", password: "Open@S3sam3!!!7" },
  { phrase: "Carpe diem", password: "Carp3@D!em!!!!7" },
  { phrase: "Eureka", password: "Eureka!Eureka!2" },
];
