export const FALLBACK_PHRASES = [
  { phrase: "To be or not to be", password: "ToBe@Not2Be!" },
  { phrase: "Look before you leap", password: "LookB4@Leap!" },
  { phrase: "Stay hungry stay foolish", password: "Stay+Hungry5!" },
  { phrase: "Actions speak louder", password: "Act!onsSp34k!" },
  { phrase: "Here comes the sun", password: "H3r3@Com3sSun!" },
  { phrase: "Life is what happens", password: "L!f3@Happens2" },
  { phrase: "May the force be with you", password: "Force@BeWithU7" },
  { phrase: "Knowledge is power", password: "Knowl3dg3@Pwr!" },
  { phrase: "Keep calm and carry on", password: "K33pCalm@On+" },
  { phrase: "The best is yet to come", password: "B3st@Y3t2Come!" },
  { phrase: "Time is money", password: "T!m3@IsMon3y$" },
  { phrase: "Love is all you need", password: "Luv@IsAllU-N33d" },
  { phrase: "Just do it", password: "Just@DoIt-888" },
  { phrase: "Think different", password: "Th!nk@D!ff3r3nt" },
  { phrase: "I have a dream", password: "I-Hav3@Dream7" },
  { phrase: "All you need is love", password: "Need@IsLuv-4" },
  { phrase: "Believe you can", password: "B3l!3v3@U-Can7" },
  { phrase: "Change the world", password: "Chang3@World!" },
  { phrase: "Dream big work hard", password: "Dream@WorkHard9" },
  { phrase: "Good vibes only", password: "GoodV!b3s@Only7" },
  { phrase: "The quick brown fox", password: "Qu!ck@BrownFox7" },
  { phrase: "Hello world", password: "H3llo@World!7" },
  { phrase: "Open sesame", password: "Op3n@S3sam3!7" },
  { phrase: "Carpe diem", password: "Carp3@D!em!7" },
  { phrase: "Eureka", password: "Eureka!Eureka!2" },
];
